### ISSUE TITLE
[Bug]: Launch Environment failed due to Region. Error Attached Below

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#145]
![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/4ffd0608-190a-4cef-85d6-d87d4713aa91)

https://facetscloud.slack.com/archives/C0710DC9AKF/p1715689071979799

![image](https://github.com/Facets-cloud/facets.cloud/assets/162995672/07f587dd-c68c-4f52-89f7-2919756af0b5)

**Comment by mbhandari31** [comment]
Needs to be replicated. @RoguedBear

**Comment by mbhandari31** [comment]
CIDR is not getting sent to the infra by backend. Needs to be checked by @bhat-akshay

**Comment by RoguedBear** [comment]
this error is caused when during the first launch attempt if somehow the VPC creation fails (in our case, hitting a hard limit for number of VPCs). Then in the following launches there's a datablock inside the gke module fetching the VPC details which were supposed to be created earlier. But since the VPC does not exist the data block reads a null vpc and hence this error.

linked PR has the data block removed entirely to explicitly force a dependency on the vpc module's outputs
