### ISSUE TITLE
[Bug]: All cloud specific fields not being set in Launch Wizard

### ISSUE THREAD

**Issue by mbhandari31** [Facets-cloud/facets.cloud#17]
**Describe the bug**
All cloud specific fields not being set in Launch Wizard

**More Details (please complete the following information):**

**Additional context**

**Comment by deploy-master404** [comment]
<img width="1298" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/158149823/1f99950e-1975-459e-ba81-93a2949d3076">

in our old launch page if we used to pre-fill region, availability zone and time zone -- we would need to do it in the current launch wizard as well, since it would fast-track the launch for the user

**Comment by deploy-master404** [comment]
- @4adway to check if the pre-fill happens when the cloud account is changed, provided the fields were filled previously. 

- @deploy-master404 to check if we can have default values set in the first time for each launch(network setup)

**Comment by mbhandari31** [comment]
Fixed.
